# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easy_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #FF4500, stop:0.5 #8A2BE2, stop:1 #FFD700\n"
"    );\n"
"    border: 8px double #FF69B4;\n"
"    border-radius: 20px;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QMainWindow::title {\n"
"    color: #FFFFFF;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 4px dashed #FFD700;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QMainWindow:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:1, y1:0, x2:0, y2:1,\n"
"        stop:0 #8A2BE2, stop:1 #FF4500\n"
"    );\n"
"    border: 8px solid #32CD32;\n"
"    padding: 20px; /* Simulate a \"puff-out\" effect */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(170, 240, 131, 121))
        self.btn_dir.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_dir.setObjectName("btn_dir")
        self.lw_files = QtWidgets.QListWidget(self.centralwidget)
        self.lw_files.setGeometry(QtCore.QRect(0, 0, 141, 501))
        self.lw_files.setStyleSheet("QListWidget {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #FF007F, stop:0.5 #7FFF00, stop:1 #007FFF\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 15px;\n"
"    color: #FFFFFF;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 16px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:0.8,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FFA500, stop:1 #FF4500\n"
"    );\n"
"    color: #000000;\n"
"    border: 2px solid #8A2BE2;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #8A2BE2, stop:1 #32CD32\n"
"    );\n"
"    color: #FFD700;\n"
"    border: 2px solid #FFFFFF;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #4B0082;\n"
"    color: #FFFF00;\n"
"    border: 3px dotted #FF69B4;\n"
"    margin-left: 15px; /* Makes it look like it \"jumps out\" */\n"
"}\n"
"")
        self.lw_files.setObjectName("lw_files")
        self.lb_image = QtWidgets.QLabel(self.centralwidget)
        self.lb_image.setGeometry(QtCore.QRect(320, 110, 621, 391))
        self.lb_image.setStyleSheet("QLabel {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #8A2BE2, stop:1 #FF4500\n"
"    );\n"
"    border: 4px double #FFD700;\n"
"    border-radius: 15px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #FFFFFF;\n"
"    padding: 15px;\n"
"    text-align: center;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    text-shadow: 2px 2px #000000; /* Fake shadow using clever text effects */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 4px dashed #FF69B4;\n"
"    color: #FFD700;\n"
"    font-size: 22px; /* Slight size increase on hover */\n"
"    transform: scale(1.1); /* Gives a popping effect */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 4px solid #696969;\n"
"    color: #D3D3D3;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.lb_image.setObjectName("lb_image")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 510, 668, 58))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_left = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_left.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_left.setObjectName("btn_left")
        self.horizontalLayout.addWidget(self.btn_left)
        self.btn_right = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_right.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_right.setObjectName("btn_right")
        self.horizontalLayout.addWidget(self.btn_right)
        self.btn_flip = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_flip.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_flip.setObjectName("btn_flip")
        self.horizontalLayout.addWidget(self.btn_flip)
        self.btn_sharp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_sharp.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_sharp.setObjectName("btn_sharp")
        self.horizontalLayout.addWidget(self.btn_sharp)
        self.btn_bw = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_bw.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:1.0,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FF4500, stop:1 #8A2BE2\n"
"    );\n"
"    border: 5px dashed #FFD700;\n"
"    border-radius: 20px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #32CD32, stop:1 #7FFFD4\n"
"    );\n"
"    border: 5px solid #FFFFFF;\n"
"    color: #FF4500;\n"
"    transform: scale(1.1); /* Simulated effect, works with animations */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    border: 5px dotted #FF69B4;\n"
"    color: #000000;\n"
"    padding-left: 15px;\n"
"    padding-top: 10px; /* Simulate a \"pushed down\" effect */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    border: 5px solid #696969;\n"
"    color: #FFFFFF;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.btn_bw.setObjectName("btn_bw")
        self.horizontalLayout.addWidget(self.btn_bw)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy Editor"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.lb_image.setText(_translate("MainWindow", "Картинка"))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_flip.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.btn_bw.setText(_translate("MainWindow", "Ч/Б"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
